### ISSUE TITLE
エフォートの単位がN*mでない

### ISSUE THREAD

**Issue by ssr-yuki** [yoshito-n-students/layered_hardware_dynamixel#1]
こんにちは。

以下の、電流とトルクを変換する部分において、電流の単位が[mA]のままトルク定数が乗じられているようです。
この結果、effortには[mN*m]の単位系で値が格納されていることになりますが、ROSのtopicではSIが推奨されているためこの実装は適切ではないと思われます。
https://github.com/yoshito-n-students/layered_hardware_dynamixel/blob/3145fb941c8b9b9817f8b327a422457316971e9d/include/layered_hardware_dynamixel/operating_mode_base.hpp#L115-L128

状態取得のみでなく、目標値についても同様です。これらに対して、1000をかける/割るの操作が必要になると考えております。

**Comment by yoshito-okada** [comment]
ありがとうございます．マージしました．
